site_name: Catalyst
site_description: Визуальный редактор графов для хемоинформатики
site_url: https://groknut.github.io/catalyst
theme:
    name: simple-blog
    language: ru
    logo: assets/icon.svg
    favicon: assets/icon.ico

nav:
    - Catalyst: index.md
    - Get started: get_started.md
    - Nodes: nodes.md
    - Demos: demos.md
