site_name: Catalyst
site_description: Визуальный редактор графов для хемоинформатики

theme:
    name: simple-blog
    language: ru

nav:
    - Catalyst: index.md
    - Nodes: nodes.md
    - Demos: demos.md
