[project]
name = "catalyst"
version = "0.1.0"
description = "Interactive graphical designer for working with chemical data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dearpygui>=2.3.1",
    "pyyaml>=6.0.3",
    "rdkit>=2026.3.1",
]

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "pytest>=9.0.3",
    "ruff>=0.15.13",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
